# Generated by Django 4.1.3 on 2023-01-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodcenters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcenter',
            name='center_type',
            field=models.CharField(default='donation', max_length=40),
        ),
    ]
